CREATE TABLE work_order (
    work_order_id UUID PRIMARY KEY,
    external_work_order_id VARCHAR(255) NOT NULL,
    title VARCHAR(255) NOT NULL,
    summary TEXT,
    description TEXT,
    work_details TEXT,
    status VARCHAR(50) NOT NULL,
    priority VARCHAR(50),
    work_order_type VARCHAR(50),
    amount DECIMAL(19,2),
    due_date TIMESTAMP,
    completion_date TIMESTAMP,
    entry_notes TEXT,
    vendor_notes TEXT,
    invoice_number VARCHAR(255),
    chargeable_to VARCHAR(255),
    call_source VARCHAR(255),
    caller_name VARCHAR(255),
    caller_contact_info VARCHAR(255),
    property_id UUID,
    unit_id UUID,
    tenant_id UUID,
    assigned_to VARCHAR(255),
    vendor_id VARCHAR(255),
    created_by UUID NOT NULL,
    created TIMESTAMP NOT NULL,
    modified_by UUID NOT NULL,
    modified TIMESTAMP NOT NULL,
    updated_source VARCHAR(255),
    created_by_name VARCHAR(255),
    modified_by_name VARCHAR(255),
    FOREIGN KEY (property_id) REFERENCES property(property_id),
    FOREIGN KEY (unit_id) REFERENCES unit(unit_id),
    FOREIGN KEY (tenant_id) REFERENCES person(person_id)
);
